### ISSUE TITLE
Repo Cloning On Windows 

### ISSUE THREAD

**Issue by timothyprevo** [timothyprevo/mytest-#3]
git-cmd. exe not giving permission to clone repository even though I have inputted cd --global commands through the terminal which should allow me to have permission to my own repo. 

Error in question after input.  git clone https://github.com/timothyprevo/mytest.git 
fatal: could not create work tree dir 'mytest': Permission denied 

repo has been cloned through GitHub app and pushing commits works without problems through RStudio

**Comment by ryantmoore** [comment]
As we discussed after class, I'll update my records to reflect your local work. Please assign me #1 as practice!
